enable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[Instagram]
apkmirror-dlurl = "https://apkmirror.com/apk/instagram/instagram-instagram/"
arch = "arm64-v8a"
included-patches = "'Limit feed to followed profiles' 'Anonymous story viewing' 'Hide navigation buttons' 'Hide suggested content' 'Open links externally' 'Disable story auto flipping'"

[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
arch = "arm64-v8a"

[Jiohotstar]
apkmirror-dlurl = "https://apkmirror.com/apk/jiostar-india-private-limited/hotstar-2"
arch = "arm64-v8a"

[News]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/google-news"
arch = "arm64-v8a"

[Photos]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/photos/"
arch = "arm64-v8a"
included-patches = "'Enable DCIM folders backup control'"

[PrimeVideo]
apkmirror-dlurl = "https://apkmirror.com/apk/amazon-mobile-llc/amazon-prime-video"
arch = "arm64-v8a"
included-patches = "'Rename shared permissions'"

[Spotify]
apkmirror-dlurl = "https://apkmirror.com/apk/spotify-ab/spotify-music-podcasts"
included-patches = "'Custom theme'"
